ƒmain() {
    ⌽("Starting complete workflow example...");
    
    // 1. Gather information from the web
    ⌽("Step 1: Gathering information from the web...");
    ιbrowser = 🌐("https://en.wikipedia.org/wiki/Rust_(programming_language)");
    
    // Extract the introduction paragraph
    ιintro = 👁(browser, "p");
    ⌽("Introduction paragraph:");
    ⌽(intro);
    
    // Save the introduction to memory
    📝("rust_intro", intro);
    
    // Close the browser
    ❌(browser);
    
    // 2. Process the information
    ⌽("Step 2: Processing the information...");
    ιstored_intro = 📖("rust_intro");
    
    // Count words
    ιwords = stored_intro.split(/\s+/);
    ιword_count = words.length;
    ⌽(`The introduction has ${word_count} words`);
    
    // Extract key terms (simplified example)
    ιkey_terms = [];
    ∀(["Rust", "programming language", "Mozilla", "performance", "safety"], λterm {
        if (stored_intro.includes(term)) {
            ＋(key_terms, term);
        }
    });
    
    ⌽("Key terms found:");
    ∀(key_terms, λterm {
        ⌽(`- ${term}`);
    });
    
    // 3. Save results to file system
    ⌽("Step 3: Saving results to file system...");
    
    // Create a directory for results
    !("mkdir -p results");
    
    // Save the introduction
    ✍("results/rust_intro.txt", stored_intro);
    
    // Save the analysis
    ιanalysis = {
        source: "Wikipedia",
        topic: "Rust Programming Language",
        word_count: word_count,
        key_terms: key_terms,
        timestamp: Date.now()
    };
    
    ✍("results/analysis.json", ⎋(analysis));
    
    // 4. Generate a report
    ⌽("Step 4: Generating a report...");
    
    ιreport = `
# Rust Programming Language Analysis
Generated on: ${new Date().toISOString()}

## Introduction
${stored_intro}

## Analysis
- Word count: ${word_count}
- Key terms: ${key_terms.join(", ")}

## Conclusion
This report was automatically generated by Anarchy Agent.
`;
    
    ✍("results/report.md", report);
    ⌽("Report generated and saved to results/report.md");
    
    // List all generated files
    ⌽("Generated files:");
    ιfiles = 📂("results");
    ∀(files, λfile {
        ⌽(`- ${file}`);
    });
    
    ⟼("Complete workflow example finished successfully");
}

main();
